### ISSUE TITLE
AddInt.wat file isn't compiled

### ISSUE THREAD

**Issue by VanDerSam** [battlelinegames/ArtOfWasm#3]
When I execute command "wat2wam AddInt.wat" the result is as below.
"
Error: abort(Error: parseWat failed:
(module
  (func (export "AddInt")
  (param $value_1 i32) (param $value_2 i32)
  (result i32)
                get_local $value_1
                get_local $value_2
                i32.add
  )
):5:3: error: unexpected token get_local, expected ).
                get_local $value_1
  ^^^^^^^^^
(module
  (func (export "AddInt")
  (param $value_1 i32) (param $value_2 i32)
  (result i32)
                get_local $value_1
                get_local $value_2
                i32.add
  )
):6:3: error: unexpected token get_local.
                get_local $value_2
  ^^^^^^^^^
). Build with -s ASSERTIONS=1 for more info.
    at process.q (C:\Users\<UserAccount>\AppData\Roaming\npm\node_modules\wat-wasm\node_modules\binaryen\index.js:54:175)
    at process.emit (events.js:215:7)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
"

I can't understand what is wrong.

**Comment by lirlia** [comment]
I faced same trouble. I tried 2 arch, but not succeeded

```
CentOS Linux release 7.9.2009 (Core)
Linux xxx 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

M1 mac BigSur
Darwin xxx 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
```

**Comment by lirlia** [comment]
my workaround to use `wabt`
- https://github.com/WebAssembly/wabt

**Comment by VanDerSam** [comment]
@lirlia Thank you for advice:)
I successfully built **wabt** in the environment Windows 10, WSL2, Ubuntu 20.04. And command **wat2wasm** works without errors.

**Comment by battlelinegames** [comment]
I've had this issue when I used PowerScript on Windows.  I was able to get it working by putting `npx` in front of the command

```
npx wat2wasm AddInt.wat
```

I don't run into this problem when using Bash or Git Bash as my shell.  Unfortunately, I didn't run into this issue until the book was going to print because I don't use PowerShell.

Sorry for the inconvenience
