### ISSUE TITLE
func_perform shows no difference

### ISSUE THREAD

**Issue by srp-at-ah** [battlelinegames/ArtOfWasm#4]
I get these results that show no significant difference between incrementing the variable internally or from an external function. The execution time for the internal call is larger than expected.
```
wasm_call time: 22
js_call time: 22
```
I built the module using `wat2wasm` from available `wabt` package for my linux distro, and also used the .wasm file in your repository. Same file size, same timings.
The code is on pp 55-59. Is there an explanation?

**Comment by battlelinegames** [comment]
The Wasm working group has been improving the performance of crossing the js/wasm boundary.  That being said, I'm surprised that it happens to have identical times.  Is it consistently the same if you run it multiple times?

Thanks for letting me know.

**Comment by srp-at-ah** [comment]
Thanks for letting me know. Below you will find a few results starting with my very first attempt. Notice that in the last executions the external calls are sometimes faster, in fact the results now oscillate between both types and remain at around 22-23 ms. But, speaking of improvements, to me it looks like the internal calls have become slower rather than the external becoming faster. In your book the values are resp. 7 and 32 ms, and my cpu is a AMD Ryzen 9 5900X (desktop) which I assume could reasonably explain why the second number is smaller for me than it is for you. Also, the number of iterations I use is exactly the same as in your book.
```
➜  ex09 - imported functions node func_perform.js 
wasm_call time: 14
js_call time: 23
➜  ex09 - imported functions node func_perform.js
wasm_call time: 58
js_call time: 80
➜  ex09 - imported functions node func_perform.js
wasm_call time: 23
js_call time: 24
➜  ex09 - imported functions node func_perform.js
wasm_call time: 23
js_call time: 23
➜  ex09 - imported functions node func_perform.js
wasm_call time: 14
js_call time: 23
➜  ex09 - imported functions node func_perform.js
wasm_call time: 21
js_call time: 22
➜  ex09 - imported functions node func_perform.js
wasm_call time: 23
js_call time: 24
➜  ex09 - imported functions node func_perform.js
wasm_call time: 18
js_call time: 23
➜  ex09 - imported functions node func_perform.js
wasm_call time: 22
js_call time: 23
➜  ex09 - imported functions node func_perform.js
wasm_call time: 21
js_call time: 23
➜  ex09 - imported functions node func_perform.js
wasm_call time: 23
js_call time: 47
➜  ex09 - imported functions node func_perform.js
wasm_call time: 22
js_call time: 23
...
➜  ex09 - imported functions node func_perform.js
wasm_call time: 22
js_call time: 26
➜  ex09 - imported functions node func_perform.js
wasm_call time: 22
js_call time: 22
➜  ex09 - imported functions node func_perform.js
wasm_call time: 23
js_call time: 22
➜  ex09 - imported functions node func_perform.js
wasm_call time: 23
js_call time: 22
```

**Comment by srp-at-ah** [comment]
I have results for the next (pp 59-65) test if you want them. There WASM is about 30-40% faster than JS and import_test about 15-20% faster than table_test. I also swapped `anyfunc` for `funcref` (after reading [this word of caution](this word of caution)) but saw no noticeable performance differences. This is not directly related to the ticket, but I did not feel like opening a new one and you seemed to be interested with my results. I apologize if this is not suitable.

**Comment by battlelinegames** [comment]
The numbers in your multiple runs are similar to what I have seen.  JavaScript's performance is generally speaking less consistent and depends on what the JIT is able to optimize depending on a lot of different factors.  Your tests have more runs where the JS calls are running about as fast or sometimes faster than the Wasm.  That is a bit different than what I saw when I was writing the chapter, which was probably about a year and a half ago.  I got a few runs where they ran about as fast, but there were fewer of those than in your data and more runs with large differences.

**Comment by srp-at-ah** [comment]
What could explain the relatively poor performance of the pure WASM tests according to you? Thanks.

**Comment by srp-at-ah** [comment]
Fine book.

**Comment by battlelinegames** [comment]
Thank you!
